import { User, Crop, Order, Notification, WeatherData, AIRecommendation, PaymentRecord } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_farmer_1',
    name: 'Ramesh Patel',
    email: 'ramesh.farmer@agriconnect.com',
    role: 'farmer',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=300',
    location: 'Nashik, Maharashtra',
    farmName: 'Patel Organic Bio-Farms',
    farmLocation: 'Village Dindori, Nashik District, Maharashtra',
    farmSizeAcres: 14.5,
    cropsGrown: ['Organic Tomatoes', 'Alphonso Mangoes', 'Basmati Rice', 'Green Chillies', 'Soybean'],
    farmerRating: 4.9,
    verificationDocuments: {
      landDocumentImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=600',
      cropApprovalDocumentImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=600',
      landImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=600',
      submittedAt: '2025-08-12',
      status: 'approved',
    },
    isVerified: true,
    status: 'active',
    createdAt: '2025-08-12',
  },
  {
    id: 'usr_farmer_2',
    name: 'Sukhwinder Singh',
    email: 'sukhwinder@agriconnect.com',
    role: 'farmer',
    phone: '+91 98123 45678',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    location: 'Ludhiana, Punjab',
    farmName: 'Golden Grain Agro Fields',
    farmLocation: 'Khanna Tehsil, Ludhiana, Punjab',
    farmSizeAcres: 28.0,
    cropsGrown: ['Sharbati Premium Wheat', 'Basmati Rice', 'Mustard Seeds', 'Maize'],
    farmerRating: 4.8,
    verificationDocuments: {
      landDocumentImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=600',
      cropApprovalDocumentImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=600',
      landImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=600',
      submittedAt: '2025-09-04',
      status: 'approved',
    },
    isVerified: true,
    status: 'active',
    createdAt: '2025-09-04',
  },
  {
    id: 'usr_farmer_3',
    name: 'Lakshmi Narayana',
    email: 'lakshmi.farms@agriconnect.com',
    role: 'farmer',
    phone: '+91 97456 12389',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    location: 'Guntur, Andhra Pradesh',
    farmName: 'Krishna Valley Spices & Chillies',
    farmLocation: 'Tenali Rural, Guntur, Andhra Pradesh',
    farmSizeAcres: 9.2,
    cropsGrown: ['Guntur Red Chilli', 'Turmeric Rhizomes', 'Cotton', 'Black Gram'],
    farmerRating: 4.7,
    verificationDocuments: {
      landDocumentImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=600',
      cropApprovalDocumentImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=600',
      landImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=600',
      submittedAt: '2025-10-15',
      status: 'approved',
    },
    isVerified: true,
    status: 'active',
    createdAt: '2025-10-15',
  },
  {
    id: 'usr_buyer_1',
    name: 'Priya Sharma',
    email: 'priya.buyer@agriconnect.com',
    role: 'buyer',
    phone: '+91 99887 76655',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    location: 'Mumbai, Maharashtra',
    businessName: 'FreshRoots Organic Superstores Ltd.',
    buyerType: 'Retailer',
    savedAddresses: [
      {
        id: 'addr_1',
        label: 'Central Distribution Hub',
        street: 'Plot 42, APMC Market Yard, Vashi',
        city: 'Navi Mumbai',
        state: 'Maharashtra',
        pincode: '400703',
        isDefault: true,
      },
      {
        id: 'addr_2',
        label: 'Andheri West Flagship Store',
        street: 'Shop 12-14, Link Road, Andheri West',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400053',
        isDefault: false,
      }
    ],
    status: 'active',
    createdAt: '2025-11-01',
  },
  {
    id: 'usr_buyer_2',
    name: 'Anand Verma',
    email: 'anand.verma@agrohub.in',
    role: 'buyer',
    phone: '+91 94567 89012',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    location: 'Bengaluru, Karnataka',
    businessName: 'Verma Agro Exports & Milling Co.',
    buyerType: 'Wholesale Distributor',
    savedAddresses: [
      {
        id: 'addr_3',
        label: 'Main Warehouse',
        street: 'Peenya Industrial Area Stage 2',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560058',
        isDefault: true,
      }
    ],
    status: 'active',
    createdAt: '2025-12-10',
  },
  {
    id: 'usr_admin_1',
    name: 'AgriConnect Admin',
    email: 'admin@agriconnect.com',
    role: 'admin',
    phone: '04562 235 000',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300',
    location: 'Sivakasi, Tamil Nadu',
    status: 'active',
    createdAt: '2025-01-01',
  }
];

export const INITIAL_CROPS: Crop[] = [
  {
    id: 'crp_101',
    farmerId: 'usr_farmer_1',
    farmerName: 'Ramesh Patel',
    farmerLocation: 'Nashik, Maharashtra',
    farmerRating: 4.9,
    farmerPhone: '+91 98765 43210',
    name: 'Organic Vine-Ripened Tomatoes',
    category: 'Fresh Vegetables',
    description: 'Pesticide-free, naturally ripened hybrid red tomatoes. Firm texture with high lycopene content, ideal for table consumption, sauces, and retail display.',
    quantity: 1200,
    unit: 'kg',
    pricePerUnit: 28,
    harvestDate: '2026-09-12',
    farmLocation: 'Patel Bio-Farms, Dindori, Nashik',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: true,
    minOrder: 50,
    shelfLifeDays: 14,
    gradeQuality: 'Grade A Premium',
    createdAt: '2026-09-12T09:00:00Z',
  },
  {
    id: 'crp_102',
    farmerId: 'usr_farmer_2',
    farmerName: 'Sukhwinder Singh',
    farmerLocation: 'Ludhiana, Punjab',
    farmerRating: 4.8,
    farmerPhone: '+91 98123 45678',
    name: 'Sharbati Royal Golden Wheat',
    category: 'Grains & Cereals',
    description: 'Single-origin premium Sharbati wheat grains from Punjab soil. Golden luster, heavy grains, superior gluten elasticity for soft chapatis.',
    quantity: 85,
    unit: 'quintal',
    pricePerUnit: 2850,
    harvestDate: '2026-08-28',
    farmLocation: 'Khanna Grain Fields, Ludhiana',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: false,
    minOrder: 5,
    shelfLifeDays: 365,
    gradeQuality: 'Grade A Premium',
    createdAt: '2026-08-29T10:30:00Z',
  },
  {
    id: 'crp_103',
    farmerId: 'usr_farmer_1',
    farmerName: 'Ramesh Patel',
    farmerLocation: 'Nashik, Maharashtra',
    farmerRating: 4.9,
    farmerPhone: '+91 98765 43210',
    name: 'Ratnagiri King Alphonso Mangoes',
    category: 'Seasonal Fruits',
    description: 'GI-tagged authentic GI Alphonso (Hapus) mangoes. Naturally grass-matured with intense sweet aroma and fiberless buttery pulp.',
    quantity: 350,
    unit: 'crates',
    pricePerUnit: 1400,
    harvestDate: '2026-09-08',
    farmLocation: 'Patel Orchards, Nashik',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: true,
    minOrder: 5,
    shelfLifeDays: 10,
    gradeQuality: 'Export Quality',
    createdAt: '2026-09-08T14:15:00Z',
  },
  {
    id: 'crp_104',
    farmerId: 'usr_farmer_3',
    farmerName: 'Lakshmi Narayana',
    farmerLocation: 'Guntur, Andhra Pradesh',
    farmerRating: 4.7,
    farmerPhone: '+91 97456 12389',
    name: 'Guntur Sannam Hot Red Chillies',
    category: 'Spices & Herbs',
    description: 'Sun-dried Sannam S4 spicy red chillies. High capsaicin pungency with deep crimson ASTA color value. Cleaned, destemmed, and bagged in moisture-barrier bags.',
    quantity: 4500,
    unit: 'kg',
    pricePerUnit: 195,
    harvestDate: '2026-08-15',
    farmLocation: 'Tenali Rural, Guntur',
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: false,
    minOrder: 100,
    shelfLifeDays: 240,
    gradeQuality: 'Export Quality',
    createdAt: '2026-08-16T11:00:00Z',
  },
  {
    id: 'crp_105',
    farmerId: 'usr_farmer_2',
    farmerName: 'Sukhwinder Singh',
    farmerLocation: 'Ludhiana, Punjab',
    farmerRating: 4.8,
    farmerPhone: '+91 98123 45678',
    name: 'Traditional 1121 XXL Basmati Rice',
    category: 'Grains & Cereals',
    description: 'Aged 2 years, extra-long slender grains that double in length on cooking. Sweet floral fragrance, completely stone-free and sortex cleaned.',
    quantity: 120,
    unit: 'quintal',
    pricePerUnit: 5200,
    harvestDate: '2026-07-20',
    farmLocation: 'Khanna Grain Fields, Ludhiana',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: false,
    minOrder: 10,
    shelfLifeDays: 730,
    gradeQuality: 'Grade A Premium',
    createdAt: '2026-07-22T08:00:00Z',
  },
  {
    id: 'crp_106',
    farmerId: 'usr_farmer_3',
    farmerName: 'Lakshmi Narayana',
    farmerLocation: 'Guntur, Andhra Pradesh',
    farmerRating: 4.7,
    farmerPhone: '+91 97456 12389',
    name: 'Organic High-Curcumin Turmeric',
    category: 'Spices & Herbs',
    description: 'Salem variety raw finger turmeric rhizomes with 5.4% lab-verified active Curcumin. Hand-harvested and washed without chemical polish.',
    quantity: 1800,
    unit: 'kg',
    pricePerUnit: 145,
    harvestDate: '2026-09-01',
    farmLocation: 'Krishna Valley, Guntur',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: true,
    minOrder: 50,
    shelfLifeDays: 300,
    gradeQuality: 'Grade A Premium',
    createdAt: '2026-09-02T15:20:00Z',
  },
  {
    id: 'crp_107',
    farmerId: 'usr_farmer_1',
    farmerName: 'Ramesh Patel',
    farmerLocation: 'Nashik, Maharashtra',
    farmerRating: 4.9,
    farmerPhone: '+91 98765 43210',
    name: 'Fresh Crisp Green Bell Peppers',
    category: 'Fresh Vegetables',
    description: 'Polyhouse greenhouse grown crunchy capsicums. Thick walls, uniform blocky 4-lobed shape, vibrant emerald green color with 21 days shelf-life.',
    quantity: 800,
    unit: 'kg',
    pricePerUnit: 42,
    harvestDate: '2026-09-14',
    farmLocation: 'Patel Polyhouse, Nashik',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: true,
    minOrder: 40,
    shelfLifeDays: 21,
    gradeQuality: 'Grade A Premium',
    createdAt: '2026-09-14T07:45:00Z',
  },
  {
    id: 'crp_108',
    farmerId: 'usr_farmer_2',
    farmerName: 'Sukhwinder Singh',
    farmerLocation: 'Ludhiana, Punjab',
    farmerRating: 4.8,
    farmerPhone: '+91 98123 45678',
    name: 'Yellow Mustard Seeds (Sarson)',
    category: 'Oilseeds',
    description: 'High oil-content (41%+) bold yellow mustard seeds. Freshly threshed, free from argemone adulteration, perfect for cold-pressed oil extraction.',
    quantity: 60,
    unit: 'quintal',
    pricePerUnit: 6400,
    harvestDate: '2026-08-10',
    farmLocation: 'Khanna Fields, Ludhiana',
    image: 'https://images.unsplash.com/photo-1628744448840-55bdb2497bd4?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    organic: false,
    minOrder: 5,
    shelfLifeDays: 365,
    gradeQuality: 'Grade B Standard',
    createdAt: '2026-08-11T13:00:00Z',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-2026-8941',
    buyerId: 'usr_buyer_1',
    buyerName: 'Priya Sharma',
    buyerEmail: 'priya.buyer@agriconnect.com',
    buyerPhone: '+91 99887 76655',
    farmerId: 'usr_farmer_1',
    farmerName: 'Ramesh Patel',
    deliveryAddress: {
      street: 'Plot 42, APMC Market Yard, Vashi',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      pincode: '400703',
    },
    items: [
      {
        cropId: 'crp_101',
        cropName: 'Organic Vine-Ripened Tomatoes',
        category: 'Fresh Vegetables',
        quantity: 250,
        unit: 'kg',
        unitPrice: 28,
        total: 7000,
        image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=600',
      },
      {
        cropId: 'crp_107',
        cropName: 'Fresh Crisp Green Bell Peppers',
        category: 'Fresh Vegetables',
        quantity: 100,
        unit: 'kg',
        unitPrice: 42,
        total: 4200,
        image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&q=80&w=600',
      }
    ],
    subtotal: 11200,
    platformFee: 224,
    deliveryFee: 450,
    totalAmount: 11874,
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    orderStatus: 'shipped',
    orderDate: '2026-09-13T10:15:00Z',
    estimatedDelivery: '2026-09-16',
    trackingNumber: 'AGC-LOG-98234',
    timeline: [
      {
        status: 'pending',
        title: 'Order Placed & Paid',
        description: 'Payment verified via Instant UPI gateway.',
        timestamp: '2026-09-13 10:15 AM',
        completed: true,
      },
      {
        status: 'confirmed',
        title: 'Farmer Confirmed Batch',
        description: 'Farmer Ramesh Patel accepted the produce harvest order.',
        timestamp: '2026-09-13 11:30 AM',
        completed: true,
      },
      {
        status: 'processing',
        title: 'Quality Graded & Packed',
        description: 'Produce sorted into ventilated corrugated crates at Nashik farm hub.',
        timestamp: '2026-09-14 08:00 AM',
        completed: true,
      },
      {
        status: 'shipped',
        title: 'In Transit via AgroCold Logistics',
        description: 'Refrigerated transit vehicle #MH-15-EC-4029 dispatched toward Navi Mumbai APMC.',
        timestamp: '2026-09-15 06:45 AM',
        completed: true,
      },
      {
        status: 'delivered',
        title: 'Final Delivery',
        description: 'Scheduled arrival at buyer destination hub.',
        timestamp: 'Pending delivery on Sep 16',
        completed: false,
      }
    ],
    notes: 'Please ensure temperature inside cargo does not exceed 12°C.',
  },
  {
    id: 'ORD-2026-8712',
    buyerId: 'usr_buyer_2',
    buyerName: 'Anand Verma',
    buyerEmail: 'anand.verma@agrohub.in',
    buyerPhone: '+91 94567 89012',
    farmerId: 'usr_farmer_2',
    farmerName: 'Sukhwinder Singh',
    deliveryAddress: {
      street: 'Peenya Industrial Area Stage 2',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560058',
    },
    items: [
      {
        cropId: 'crp_105',
        cropName: 'Traditional 1121 XXL Basmati Rice',
        category: 'Grains & Cereals',
        quantity: 20,
        unit: 'quintal',
        unitPrice: 5200,
        total: 104000,
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600',
      }
    ],
    subtotal: 104000,
    platformFee: 2080,
    deliveryFee: 3200,
    totalAmount: 109280,
    paymentMethod: 'netbanking',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    orderDate: '2026-09-05T14:20:00Z',
    estimatedDelivery: '2026-09-11',
    trackingNumber: 'AGC-LOG-74512',
    timeline: [
      {
        status: 'pending',
        title: 'Order Placed',
        description: 'Payment settled via RTGS/NetBanking.',
        timestamp: '2026-09-05 02:20 PM',
        completed: true,
      },
      {
        status: 'confirmed',
        title: 'Confirmed by Farmer',
        description: 'Grain bags palletized for interstate transit.',
        timestamp: '2026-09-05 05:00 PM',
        completed: true,
      },
      {
        status: 'processing',
        title: 'Moisture Tested & Sealed',
        description: 'Certified moisture level 11.8% at Ludhiana depot.',
        timestamp: '2026-09-06 10:00 AM',
        completed: true,
      },
      {
        status: 'shipped',
        title: 'Dispatched via Rail Freight',
        description: 'Container boarded train to Bengaluru ICD.',
        timestamp: '2026-09-07 09:00 AM',
        completed: true,
      },
      {
        status: 'delivered',
        title: 'Successfully Delivered',
        description: 'Received at Peenya warehouse with electronic signoff.',
        timestamp: '2026-09-11 04:10 PM',
        completed: true,
      }
    ]
  },
  {
    id: 'ORD-2026-9034',
    buyerId: 'usr_buyer_1',
    buyerName: 'Priya Sharma',
    buyerEmail: 'priya.buyer@agriconnect.com',
    buyerPhone: '+91 99887 76655',
    farmerId: 'usr_farmer_3',
    farmerName: 'Lakshmi Narayana',
    deliveryAddress: {
      street: 'Shop 12-14, Link Road, Andheri West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400053',
    },
    items: [
      {
        cropId: 'crp_104',
        cropName: 'Guntur Sannam Hot Red Chillies',
        category: 'Spices & Herbs',
        quantity: 150,
        unit: 'kg',
        unitPrice: 195,
        total: 29250,
        image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=600',
      }
    ],
    subtotal: 29250,
    platformFee: 585,
    deliveryFee: 650,
    totalAmount: 30485,
    paymentMethod: 'card',
    paymentStatus: 'paid',
    orderStatus: 'processing',
    orderDate: '2026-09-14T16:40:00Z',
    estimatedDelivery: '2026-09-18',
    trackingNumber: 'AGC-LOG-91022',
    timeline: [
      {
        status: 'pending',
        title: 'Order Placed',
        description: 'Payment authorized.',
        timestamp: '2026-09-14 04:40 PM',
        completed: true,
      },
      {
        status: 'confirmed',
        title: 'Confirmed by Farmer',
        description: 'Lakshmi Narayana verified stock availability.',
        timestamp: '2026-09-14 06:10 PM',
        completed: true,
      },
      {
        status: 'processing',
        title: 'Packaging & Weight Verification',
        description: 'Chillies undergoing final dry-pack packaging.',
        timestamp: '2026-09-15 09:30 AM',
        completed: true,
      },
      {
        status: 'shipped',
        title: 'Awaiting Courier Pickup',
        description: 'Courier assigned, dispatch scheduled.',
        timestamp: 'Expected Sep 16',
        completed: false,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Delivery to Andheri store.',
        timestamp: 'Expected Sep 18',
        completed: false,
      }
    ]
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    recipientId: 'usr_farmer_1',
    title: 'New Order Received',
    message: 'Priya Sharma has placed order #ORD-2026-8941 for 250 kg Tomatoes & 100 kg Bell Peppers.',
    type: 'order',
    read: false,
    createdAt: '2026-09-13T10:16:00Z',
    actionUrl: '/farmer/orders',
  },
  {
    id: 'notif_2',
    recipientId: 'usr_farmer_1',
    title: 'Weather Warning: Rain Expected',
    message: 'Moderate to heavy showers expected in Nashik tomorrow afternoon. Protect open grain and postpone pesticide spraying.',
    type: 'weather',
    read: false,
    createdAt: '2026-09-15T06:00:00Z',
    actionUrl: '/farmer/weather',
  },
  {
    id: 'notif_3',
    recipientId: 'usr_farmer_1',
    title: 'Crop Advisory Update',
    message: 'High market demand detected for Organic Sweet Corn in Maharashtra. Suitability score 94%.',
    type: 'ai_recommendation',
    read: true,
    createdAt: '2026-09-14T11:20:00Z',
    actionUrl: '/farmer/recommendations',
  },
  {
    id: 'notif_4',
    recipientId: 'usr_buyer_1',
    title: 'Order Dispatched',
    message: 'Your order #ORD-2026-8941 has departed from Nashik and is in refrigerated transit to Navi Mumbai.',
    type: 'order',
    read: false,
    createdAt: '2026-09-15T06:46:00Z',
    actionUrl: '/buyer/track/ORD-2026-8941',
  },
  {
    id: 'notif_5',
    recipientId: 'all',
    title: 'AgriConnect Platform Notice',
    message: 'Direct UPI instant settlement is now live for all registered farmer cooperative accounts.',
    type: 'system',
    read: true,
    createdAt: '2026-09-10T12:00:00Z',
  }
];

export const MOCK_WEATHER_DATA: Record<string, WeatherData> = {
  'Nashik, Maharashtra': {
    location: 'Nashik, Maharashtra',
    current: {
      temp: 27,
      condition: 'Scattered Showers',
      icon: 'CloudRain',
      humidity: 78,
      rainfallMm: 14.2,
      windSpeedKmh: 16,
      uvIndex: 5,
      soilMoisturePercent: 68,
      feelsLike: 29,
    },
    forecast: [
      { day: 'Today', date: 'Sep 15', maxTemp: 29, minTemp: 21, condition: 'Scattered Showers', icon: 'CloudRain', rainProb: 75 },
      { day: 'Tomorrow', date: 'Sep 16', maxTemp: 28, minTemp: 20, condition: 'Heavy Rain', icon: 'CloudLightning', rainProb: 90 },
      { day: 'Thursday', date: 'Sep 17', maxTemp: 30, minTemp: 22, condition: 'Partly Cloudy', icon: 'CloudSun', rainProb: 30 },
      { day: 'Friday', date: 'Sep 18', maxTemp: 31, minTemp: 22, condition: 'Sunny & Warm', icon: 'Sun', rainProb: 10 },
      { day: 'Saturday', date: 'Sep 19', maxTemp: 32, minTemp: 23, condition: 'Clear Sky', icon: 'Sun', rainProb: 5 },
    ],
    alerts: [
      {
        id: 'w_alt_1',
        severity: 'warning',
        title: 'Heavy Rainfall Warning',
        description: 'Rain intensity of 25-45 mm anticipated over Nashik & Dindori talukas within 24 hours. Ensure drainage trenches are clear.',
        time: 'Valid until 16 Sep, 6:00 PM',
      }
    ],
    farmingAdvice: [
      {
        crop: 'Tomatoes & Vegetables',
        recommendation: 'Pause overhead drip irrigation for 48 hours. Ensure raised beds are drained to prevent root rot.',
        urgency: 'high',
      },
      {
        crop: 'Pesticide Application',
        recommendation: 'Postpone chemical spray schedule until Friday when dry weather returns.',
        urgency: 'medium',
      },
      {
        crop: 'Stored Grains',
        recommendation: 'Check moisture proof tarping on outdoor grain storage platforms.',
        urgency: 'high',
      }
    ]
  },
  'Ludhiana, Punjab': {
    location: 'Ludhiana, Punjab',
    current: {
      temp: 33,
      condition: 'Sunny & Clear',
      icon: 'Sun',
      humidity: 52,
      rainfallMm: 0.0,
      windSpeedKmh: 11,
      uvIndex: 8,
      soilMoisturePercent: 44,
      feelsLike: 36,
    },
    forecast: [
      { day: 'Today', date: 'Sep 15', maxTemp: 34, minTemp: 24, condition: 'Clear Sky', icon: 'Sun', rainProb: 5 },
      { day: 'Tomorrow', date: 'Sep 16', maxTemp: 35, minTemp: 25, condition: 'Sunny & Dry', icon: 'Sun', rainProb: 0 },
      { day: 'Thursday', date: 'Sep 17', maxTemp: 34, minTemp: 24, condition: 'Mostly Sunny', icon: 'CloudSun', rainProb: 10 },
      { day: 'Friday', date: 'Sep 18', maxTemp: 33, minTemp: 23, condition: 'Partly Cloudy', icon: 'CloudSun', rainProb: 15 },
      { day: 'Saturday', date: 'Sep 19', maxTemp: 32, minTemp: 22, condition: 'Light Breeze', icon: 'Wind', rainProb: 5 },
    ],
    alerts: [],
    farmingAdvice: [
      {
        crop: 'Paddy / Basmati Rice',
        recommendation: 'Maintain 2-3 inches standing water in fields during grain filling stage. Schedule evening irrigation.',
        urgency: 'high',
      },
      {
        crop: 'Mustard Sowing Prep',
        recommendation: 'Ideal soil temperature window approaching. Prepare nursery beds with organic compost.',
        urgency: 'medium',
      }
    ]
  },
  'Guntur, Andhra Pradesh': {
    location: 'Guntur, Andhra Pradesh',
    current: {
      temp: 31,
      condition: 'Partly Cloudy',
      icon: 'CloudSun',
      humidity: 65,
      rainfallMm: 2.1,
      windSpeedKmh: 14,
      uvIndex: 7,
      soilMoisturePercent: 55,
      feelsLike: 34,
    },
    forecast: [
      { day: 'Today', date: 'Sep 15', maxTemp: 32, minTemp: 25, condition: 'Partly Cloudy', icon: 'CloudSun', rainProb: 20 },
      { day: 'Tomorrow', date: 'Sep 16', maxTemp: 33, minTemp: 26, condition: 'Humid & Warm', icon: 'CloudSun', rainProb: 25 },
      { day: 'Thursday', date: 'Sep 17', maxTemp: 31, minTemp: 24, condition: 'Isolated Showers', icon: 'CloudRain', rainProb: 40 },
      { day: 'Friday', date: 'Sep 18', maxTemp: 30, minTemp: 24, condition: 'Overcast', icon: 'Cloud', rainProb: 35 },
      { day: 'Saturday', date: 'Sep 19', maxTemp: 32, minTemp: 25, condition: 'Pleasant', icon: 'Sun', rainProb: 10 },
    ],
    alerts: [],
    farmingAdvice: [
      {
        crop: 'Chilli & Turmeric',
        recommendation: 'Inspect underside of leaves for mite or thrip activity in current humid conditions. Apply neem bio-formulation.',
        urgency: 'high',
      },
      {
        crop: 'Cotton Crops',
        recommendation: 'Ensure adequate drainage in black cotton soil to prevent waterlogging around square formation.',
        urgency: 'medium',
      }
    ]
  }
};

export const SAMPLE_AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'ai_rec_1',
    cropName: 'Golden Sweet Corn (Hybrid Syngenta)',
    cropImage: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&q=80&w=600',
    suitabilityScore: 96,
    expectedGrowingPeriod: '80 - 90 Days',
    expectedYield: '65 - 80 Quintals / Acre',
    marketDemand: 'Very High',
    waterRequirement: 'Medium',
    profitPotential: '₹80,000 - ₹1,40,000 / acre',
    reason: 'Your soil pH (6.8) and expected seasonal temperatures (22°C - 31°C) match the optimal sweet corn germination profile. Local food processors in nearby urban clusters are offering premium advance buyback contracts.',
    suggestedAction: 'Seed pre-soaking with bio-stimulants followed by broad-bed furrow sowing with 60cm spacing.',
    companionCrops: ['Bush Beans', 'Pumpkins', 'Soybean'],
  },
  {
    id: 'ai_rec_2',
    cropName: 'Bell Peppers / Capsicum (Indam Yellow/Red)',
    cropImage: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&q=80&w=600',
    suitabilityScore: 92,
    expectedGrowingPeriod: '110 - 130 Days',
    expectedYield: '14 - 18 Tons / Acre',
    marketDemand: 'High',
    waterRequirement: 'Medium',
    profitPotential: '₹80,000 - ₹1,40,000 / acre',
    reason: 'Well-drained loamy soil with 70% humidity provides ideal conditions for colored capsicums. Wholesale prices currently trending at 35% above the 5-year average.',
    suggestedAction: 'Establish shade-netting or polyhouse micro-sprinklers to regulate heat during peak noon hours.',
    companionCrops: ['Marigold (Nematode control)', 'Basil', 'Onions'],
  },
  {
    id: 'ai_rec_3',
    cropName: 'Organic Ginger (Rio-De-Janeiro Variety)',
    cropImage: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600',
    suitabilityScore: 88,
    expectedGrowingPeriod: '210 - 240 Days',
    expectedYield: '8 - 10 Tons / Acre',
    marketDemand: 'High',
    waterRequirement: 'High',
    profitPotential: '₹60,000 - ₹95,000 / acre',
    reason: 'Rich organic content in soil paired with monsoon humidity makes rhizome multiplication rapid with zero synthetic chemical requirements.',
    suggestedAction: 'Apply neem cake and trichoderma enriched farmyard manure before ridge formation.',
    companionCrops: ['Maize (Intercrop shade)', 'Chilli', 'Turmeric'],
  },
  {
    id: 'ai_rec_4',
    cropName: 'Export-Grade Green Seedless Grapes',
    cropImage: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&q=80&w=600',
    suitabilityScore: 85,
    expectedGrowingPeriod: 'Perennial (Pruning Cycle 120 Days)',
    expectedYield: '10 - 12 Tons / Acre',
    marketDemand: 'Very High',
    waterRequirement: 'Low',
    profitPotential: '₹80,000 - ₹1,40,000 / acre',
    reason: 'High solar radiation and temperature variance in current agro-climatic zone promotes brix sweetness levels exceeding 18° Brix.',
    suggestedAction: 'Perform foundation pruning followed by gibberellic acid berry elongation treatment.',
    companionCrops: ['Mustard cover-crop', 'Clover'],
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'PAY-TXN-10842',
    orderId: 'ORD-2026-8941',
    buyerName: 'Priya Sharma (FreshRoots)',
    farmerName: 'Ramesh Patel',
    amount: 11874,
    platformCommission: 224,
    netFarmerPayout: 11200,
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    payoutStatus: 'escrow',
    date: '2026-09-13 10:15 AM',
    transactionRef: 'UPI/2609139824/HDFC',
  },
  {
    id: 'PAY-TXN-10799',
    orderId: 'ORD-2026-8712',
    buyerName: 'Anand Verma (Verma Agro)',
    farmerName: 'Sukhwinder Singh',
    amount: 109280,
    platformCommission: 2080,
    netFarmerPayout: 104000,
    paymentMethod: 'netbanking',
    paymentStatus: 'paid',
    payoutStatus: 'processed',
    date: '2026-09-05 02:22 PM',
    transactionRef: 'NEFT/RBIPUNJ90123/SBI',
  },
  {
    id: 'PAY-TXN-10901',
    orderId: 'ORD-2026-9034',
    buyerName: 'Priya Sharma (FreshRoots)',
    farmerName: 'Lakshmi Narayana',
    amount: 30485,
    platformCommission: 585,
    netFarmerPayout: 29250,
    paymentMethod: 'card',
    paymentStatus: 'paid',
    payoutStatus: 'escrow',
    date: '2026-09-14 04:42 PM',
    transactionRef: 'CARD/VISA-4242-AUTH',
  }
];
